my_list = []
my_list.append(5)
my_list.append(8)
my_list.append(12)
my_list.append(15)
my_list.append(20)
print(my_list)
print("Index of 12 is : ", my_list.index(12))
print("No of occurence of element 15 is ", my_list.count(15))
m = my_list.pop()
print("popped element is: ", m)
print("list after popping last element: ", my_list)
my_list.extend([45, 30, 70])
print("List after extending", my_list)
my_list.sort()
print("List after sorting in ascending order: ", my_list)
my_list.reverse()
print("List after reversing in ascending order: ", my_list)
